<?php

abstract class Product
{

    private $product = [];

    public abstract function getProduct();
}


class Makanan extends Product
{
    private $product = [
        "Soto" => [4.7,"assets/img-soto.jpg","Sulit","<b>Bahan</b> :<br>1/2 ekor ayam kampung, potong dua<br>1.5 liter air<br>3 sdm minyak sayur<br>1 batang serai, memarkan<br>2 lembar daun salam<br>2 lembar daun jeruk<br><br><b>Bumbu Halus </b>:<br>5 butir bawang putih<br>3 siung bawang merah<br>4 butir kemiri<br>3 cm kunyit<br>1 cm jahe<br>1/2 sdt merica butiran<br>2 sdt garam<br><br><b>Pelengkap </b>:<br>100 g tauge<br>100 g suun, seduh air panas<br>2 butir telur rebus<br>2 sdm daun bawang<br>4 sdm bawang merah goreng<br>4 sdm sambal rawit<br>2 butir jeruk nipis, potong-potong",["Rebus babat dengan 2 liter air selama 90 menit hingga empuk. Tiriskan babat dan buang air rebusannya. Potong-potong babat jadi ukuran kecil. Sisihkan.","Panaskan minyak. Tumis bumbu halus bersama daun salam, daun jeruk, serai, lengkuas, cengkeh, dan kapulaga hingga harum.", "Masukkan babat. Aduk rata.", "Tuang santan dan air. Aduk rata.", "Bumbui dengan garam, merica, kaldu bubuk, dan gula. Aduk rata dan masak hingga mendidih.", "Masukkan daun bawang, tauge, tomat, dan bawang merah goreng. Aduk sebentar hingga tauge setengah matang. Angkat.", "Siap disajikan."]],
        "Sate" => [4.9,"assets/img-sate.jpg", "Sedang", "<b>Bahan : </b><br>Daging kambing, potong dadu 2 cm - 500 gram <br>Tusuk sate, rendam dalam air lalu tiriskan - 20 buah <br><br><b>Bumbu Olesan : </b><br>Bawang putih, haluskan - 2 siung <br>Ketumbar halus - 1/2 sdt<br>Merica halus - 1/4 sdt<br>Kecap manis - 100 ml <br>Air perasan jeruk nipis - secukupnya<br><br><b>Pelengkap : </b><br>Kubis, iris halus - 50 gram<br>Tomat merah, potong - 2 buah<br>Cabai rawit, iris - 10 buah<br>Bawang merah, iris - 10 butir<br>Kecap manis - 5 sdm<br>Jeruk nipis, belah jadi 4 - 1 buah<br>Acar timun - secukupnya<br>", ["Tusuk daging dengan tusukan sate. Isi setiap tusukan dengan 4 potong daging. Sisihkan.","Dalam wadah, campur semua bahan olesan lalu oleskan ke daging sate.","Bakar sate di atas bara api sambil sesekali dioles bumbu oles. Bakar hingga berwarna kecoklatan, matang, dan harum. Angkat.","Tata semua bahan pelengkap (Acar timun) dan sate di atas piring saji. Tuang kecap manis di atas sate. Siap disajikan."]],
        "Ayam Goreng" => [4.8,"assets/img-ayamgoreng.jpg", "Mudah","<b>Bahan :</b><br>Ayam, potong sesuai selera - 500 gram<br>Air jeruk nipis - 1 sdm<br>Minyak wijen - 1 sdm<br>Saus tiram - 1 sdm<br>Kecap ikan - 1 sdm<br>Garam - 1/2 sdt<br>Gula - 1 sdm<br>Tepung terigu - 3 sdm<br><br><b>Bumbu Halus :</b><br>Terasi - 12 gram<br>Bawang putih - 3 siung<br>Bawang merah - 2 siung<br>",["Dalam wadah masukan ayam, air jeruk nipis, dan bumbu halus. Tambahkan minyak wijen, saus tiram, kecap ikan, gula dan garam secukupnya.", "Marinasi ayam yang telah dibumbui selama 30 menit.", "Sebelum digoreng taburi tepung terigu pada ayam kemudian aduk rata.", "Panaskan minyak goreng dan goreng hingga berubah warna.", "Setelah matang dan kecoklatan, angkat dan tiriskan. Siap disajikan."]],
        "Nasi Goreng" => [4.9, "assets/img-nasigoreng.jpg", "Mudah","<b>Bahan:</b><br>1 buah paha ayam atas bawah rebus, suwir ayamnya<br>2 buah telur, kocok lepas<br>150 g udang tanpa kulit<br>5 buah bakso sapi, potong-potong<br>5 buah bakso ikan, potong-potong<br>500 g nasi putih<br>2 sdm kecap manis Bango<br>1 sdt garam<br>1/2 sdt gula pasir<br>1 buah daun bawang, iris tipis<br>1 1/2 sdm bawang goreng untuk taburan<br>3 sdm minyak goreng untuk menumis<br><br><b>Bahan Tumbuk Kasar:</b><br>1 sdt terasi, bakar<br>3 buah cabai merah besar<br>3 buah cabai merah keriting<br>2 siung bawang putih<br>6 butir bawang merah<br><br><b>Bahan Pelengkap:</b><br>3 buah telur ceplok<br>", ["Uleg halus bawang merah, bawang putih, dan kemiri. Tambahkan minyak wijen, kemudian tumis bumbu hingga harum.", "Masukkan telur, kemudian orak arik. Setelah telur matang, masukkan nasi, sawi, dan ayam goreng yang sudah disuwir. Aduk nasi hingga rata.", "Bumbui dengan garam, merica bubuk, dan kecap manis. Aduk-aduk hingga bumbu merata, koreksi rasanya.", "Setelah matang, siap disajikan dengan bawang goreng, telur ceplok, kerupuk udang, irisan mentimun dan tomat, serta acar."]],
        "Mie Goreng" => [4.7, "assets/img-miegoreng.jpg", "Mudah", "<b>Bahan:</b><br>200 gr mie kuning kering<br>daun bawang secukupnya, potong-potong<br><br><b>Bahan:</b><br>2 sdm kecap manis<br>1 sdm kecap asin<br>1 sdt saus cabai<br>2 siung bawang putih, haluskan<br>1 siung bawang merah, haluskan<br>1/4 sdt kaldu bubuk<br>garam dan lada bubuk secukupnya<br>",
        ["Panaskan minyak. Tumis bumbu halus hingga harum.", "Masukkan orak-arik telur, lalu aduk rata.", "Masukkan ayam suwir, tauge, dan caisin. Aduk rata." ,"Masukkan nasi dan mie. Aduk rata.", "Bumbui garam, gula, lada bubuk, dan kecap. Aduk rata.", "Masukkan irisan daun bawang dan cabai merah besar. Aduk rata dan masak hingga daun bawang layu. Angkat."]]
    ];  

    public function getProduct(){
        return $this->product;
    }

}


class Minuman extends Product
{
    private $product = [
        "Lemon Tea" => [4.5, "assets/img-lemontea.jpg", "Mudah","<b>Bahan:</b><br>Teh hitam - 2 sdm<br>Air untuk seduh teh - 200 ml<br>Gula pasir - 50 gram<br>Air untuk membuat sirup gula - 200 ml<br>Es batu - 200 gram<br>Madu - 2 sdm<br>Jeruk lemon lokal - 2 buah<br>",["Buat Sirup Gula: Masak air sampai mendidih, masukkan gula pasir, aduk sampai larut, saring dan biarkan dingin.", "Masak air sampai mendidih, masukkan teh, aduk sebentar, matikan api.", "Biarkan 3 menit, kemudian saring dan dinginkan.", "Peras 1,5 buah lemon.", "Iris setengah bagian sisanya.", "Siapkan teko, masukkan seduhan teh, sirup gula, perasan lemon, dan madu, aduk rata." ,"Sajikan di gelas saji dengan es batu dan irisan lemon."]],
        "Es Doger" => [4.7, "assets/img-esdoger.jpg", "Mudah","<b>Bahan: </b><br>Santan - 1 liter<br>Gula pasir - 150 gram<br>Garam - 1/2 sdt<br>Pasta doger - 2 sdm<br>Daun pandan, simpulkan - 2 helai<br><br><b>Pelengkap: </b><br>Tape singkong - 100 gram<br>Tape ketan - 100 gram<br>Alpukat - 1 buah<br>Roti tawar, potong dadu - 2 helai<br>Kental manis - 4 sdm<br>",["Campurkan semua bahan masak dengan api sedang hingga mendidih sambil terus diaduk agar santan tidak pecah. Koreksi rasa jika sudah pas matikan api.", "Letakkan dalam wadah tertutup lalu simpan ke dalam freezer selama 2 jam.", "Siapkan bahan pelengkap, ambil es doger dalam freezer serut dengan menggunakan sendok lalu tuang dalam wadah.", "Tambahkan tape singkong, tape ketan, alpukat dan roti tawar lalu siram dengan kental manis. Selesai selamat mencoba."]],
        "Es Buah" => [4.9, "assets/img-esbuah.jpg", "Sulit","<b>Bahan: </b><br>Buah pepaya potong dadu - 200 gram<br>Nanas, kupas, buang tengahnya lalu potong potong dadu - 200 gram<br>Melon potong dadu - 200 gram<br>Anggur potong potong - 200 gram<br>Buah naga potong dadu - 200 gram<br>Gula pasir - 500 gram<br>Air - 2 liter", ["Siapkan buah pepaya, nanas, melon, dan buah naga. Kupas buah - buah tersebut dari kulitnya, lalu potong kecil-kecil jadi bentuk dadu. Sisihkan.", "Cuci bersih anggur lalu belah jadi dua bagian tiap buahnya. Buang bijinya dan sisihkan.", "Dalam panci, rebus air hingga mendidih. Tambahkan gula pasir lalu aduk hingga larut. Biarkan hingga mendidih kembali. Angkat dan dinginkan.", "Masukkan semua buah Yang sudah dipotong ke dalam air gula. Simpan dalam kulkas dan diamkan minimal 1 jam.", "Siap disajikan."]],
        "Es Degan" => [4.7, "assets/img-esdegan.jpg", "Sedang","<b>Bahan: </b><br>Daging kelapa muda (serutan) - 250 gram<br>Air kelapa - 600 ml<br>Air perasan lemon - 2 sdm<br>Sirup coco pandan - 6 sdm<br>Es batu - secukupnya<br>", ["Langkah pertama, siapkan amdahing kelapa yang sudah diseruti. Lalu taruh dalam wadah besar." ,"Dalam wadah yang sama, tuang air kelapa. Tambahkan perasan jeruk lemon dan sirup. Campur semua bahan lalu aduk hingga rata." ,"Tuang ke dalam gelas saji dan tambahkan es batu." ,"Siap disajikan"]],
        "Es Jeruk" => [4.5, "assets/img-esjeruk.jpg", "Mudah", "<b>Bahan:</b><br>1 kg jeruk<br>1 bungkus jelly plain (masak sesuai petunjuk)<br>1/2 bungkus pakai susu kental manis<br>1/2 bungkusnya pakai air bunga telang<br>Selasih secukupnya (rendam air panas dan tiriskan)<br>Es batu secukupnya<br><br><b>Sirup:</b><br>5 sdm gula pasir<br>100 cc air", ["Siapkan wadah, masukkan gula pasir dan 50 ml air, aduk sampai gula larut." ,"Masukkan air jeruk nipis, daun mint, irisan jeruk nipis, dan es batu, tuang air soda, aduk sedikit, siap disajikan." ,"Pada bibir gelas bisa sedikit dibasahi dan tempel dengan sedikit garam. Campuran rasa asin garam dan asam dari jeruk nipis memberikan sensasi lebih segar ketika meminumnya."]],
    ];
    public function getProduct(){
        return $this->product;
    }
}
